services:
  database:
    container_name: tcgc-bd
    image: postgres:latest
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
    networks:
      - tcgc-network

  gateway:
    container_name: tcgc-gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    image: gateway:dev
    ports:
      - "8180:8180"
    environment:
      - USER_API_URL
      - CARD_API_URL
    volumes:
      - ./gateway:/app
    depends_on:
      - keycloak
    networks:
      - tcgc-network

  user-service:
    container_name: tcgc-user-api
    build:
      context: user-service
      dockerfile: Dockerfile
    image: user-service:dev
    ports:
      - "8181:8181"
    environment:
      - POSTGRES_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./user-service:/app
      - ./core:/core
    depends_on:
      - database
      - gateway
    networks:
      - tcgc-network

  card-service:
    container_name: tcgc-card-api
    build:
      context: card-service
      dockerfile: Dockerfile
    image: card-service:dev
    ports:
      - "8182:8182"
    environment:
      - POSTGRES_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./card-service:/app
      - ./core:/core
    depends_on:
      - database
      - gateway
    networks:
      - tcgc-network

  keycloak:
    container_name: tcgc-keycloak
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      - KC_HOSTNAME_PORT
      - KC_HOSTNAME_STRICT_BACKCHANNEL
      - KC_DB
      - KC_DB_URL
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_HEALTH_ENABLED
      - KC_LOG_LEVEL
      - KEYCLOAK_IMPORT
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [ "start-dev", "--http-port 7080", "--https-port 7443", "--import-realm" ]
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "7080:7080"
      - "7443:7443"
    depends_on:
      - database
    networks:
      - tcgc-network

  liquibase:
    container_name: tcgc-liquibase
    build:
      context: database
      dockerfile: Dockerfile
    image: liquibase:dev
    environment:
      - POSTGRES_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./database:/app
    depends_on:
      - database
    networks:
      - tcgc-network

networks:
  tcgc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/28