spring:
  application:
    name: tcgc-gateway
  security: ## Security
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.25.0.3:7080/realms/realm-security
          jwk-set-uri: http://172.25.0.3:7080/realms/realm-security/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: realm-security
            client-secret: Jk51JMNjXYRkAO9rZCEY18zhFyaSX0kc
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://172.25.0.3:7080/realms/realm-security
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay=
          routes:
            - id: card-api
              uri: ${CARD_API_URL:http://localhost:8182}
              predicates:
                - Path=/card/**
            - id: user-api
              uri: ${USER_API_URL:http://localhost:8183}
              predicates:
                - Path=/user/**
#          filters:
#            - StripPrefix=1
#            - RemoveRequestHeader=Cookie
#            - RemoveRequestHeader=Set-Cookie
#            - RemoveRequestHeader=Authorization
#            - AddRequestHeader=Authorization, Bearer {jwt.token.value}
#      discovery:
#        locator:
#          enabled: true


## Application port
server:
  port: 8180

## Security
jwt:
  auth:
    converter:
      resource-id: realm-security
      principle-attribute: preferred_username

## Logging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
