spring:
  application:
    name: tcgc-gateway
  security: ## Security
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://localhost:8180/realms/tcg-realm}
          jwk-set-uri: ${KC_JWK_SET_URI:http://localhost:8180/realms/tcg-realm/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID:tcgc-client}
            client-secret: ${KC_CLIENT_SECRET:secret}
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI:http://localhost:8180/realms/tcg-realm}
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay=
          routes:
            - id: card-api
              uri: ${CARD_API_URL:http://localhost:8182}
              predicates:
                - Path=/card/**
            - id: category-api
              uri: ${CARD_API_URL:http://localhost:8182}
              predicates:
                - Path=/category/**
            - id: user-api
              uri: ${USER_API_URL:http://localhost:8183}
              predicates:
                - Path=/user/**
#          filters:
#            - StripPrefix=1
#            - RemoveRequestHeader=Cookie
#            - RemoveRequestHeader=Set-Cookie
#            - RemoveRequestHeader=Authorization
#            - AddRequestHeader=Authorization, Bearer {jwt.token.value}
#      discovery:
#        locator:
#          enabled: true


## Application port
server:
  port: 8180

## Security
jwt:
  auth:
    converter:
      resource-id: tcgc-client
      principle-attribute: preferred_username

## Logging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
