spring:
  application:
    name: tcgc-user-api
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://172.17.0.3:5432/tcg_catalog}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari: ## default connection pool
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: catalogs
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KC_JWK_SET_URI:http://localhost:8180/realms/tcg-realm/protocol/openid-connect/certs}

## Application port
server:
  port: 8181

## Logging
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG