spring:
  application:
    name: tcgc-card-api
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://172.17.0.3:5432/tcg_catalog}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari: ## default connection pool
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: catalogs
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://172.25.0.3:7080/realms/realm-security/protocol/openid-connect/certs

## Application port
server:
  port: 8182

## Logging
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

tcgc:
  url:
    user: ${USER_API_URL:http://localhost:8181/tcgc-user-api}
